/**
 * Airline & OTA logo utilities for all LetsFG connectors.
 *
 * Airlines  → Kiwi CDN by IATA code:  https://images.kiwi.com/airlines/64/{IATA}.png
 * OTAs      → Google favicon service:  https://www.google.com/s2/favicons?domain={domain}&sz=64
 */

// ── Airlines: connector name → IATA code ──────────────────────────────────────
export const CONNECTOR_IATA: Record<string, string> = {
  aegean:               'A3',
  aerlingus:            'EI',
  aerolineas:           'AR',
  airarabia:            'G9',
  airasia:              'AK',
  airasiamove:          'AK',
  airasiax:             'D7',
  airbaltic:            'BT',
  airbusan:             'BX',
  aircairo:             'SM',
  aircalin:             'SB',
  aircanada:            'AC',
  airchina:             'CA',
  aireuropa:            'UX',
  airfrance:            'AF',
  airgreenland:         'GL',
  airindia:             'AI',
  airindiaexpress:      'IX',
  airmauritius:         'MK',
  airnewzealand:        'NZ',
  airniugini:           'PX',
  airnorth:             'TL',
  airpeace:             'P4',
  airserbia:            'JU',
  airseychelles:        'HM',
  airtahitinui:         'TN',
  airtransat:           'TS',
  airvanuatu:           'NF',
  akasa:                'QP',
  alaska:               'AS',
  allegiant:            'G4',
  american:             'AA',
  arajet:               'DM',
  asiana:               'OZ',
  austrian:             'OS',
  avelo:                'XP',
  avianca:              'AV',
  azerbaijanairlines:   'J2',
  azoresairlines:       'S4',
  azul:                 'AD',
  bangkokairways:       'PG',
  batikair:             'ID',
  biman:                'BG',
  breeze:               'MX',
  britishairways:       'BA',
  brusselsairlines:     'SN',
  caribbeanairlines:    'BW',
  cathay:               'CX',
  cebupacific:          '5J',
  chinaairlines:        'CI',
  chinaeastern:         'MU',
  chinasouthern:        'CZ',
  citilink:             'QG',
  condor:               'DE',
  copa:                 'CM',
  cyprusairways:        'CY',
  delta:                'DL',
  discover:             '4Y',
  easyjet:              'U2',
  egyptair:             'MS',
  elal:                 'LY',
  emirates:             'EK',
  ethiopian:            'ET',
  etihad:               'EY',
  eurowings:            'EW',
  evaair:               'BR',
  fijiairways:          'FJ',
  finnair:              'AY',
  flair:                'F8',
  flyadeal:             'F3',
  flyarystan:           'KC',
  flybondi:             'FO',
  flydubai:             'FZ',
  flynas:               'XY',
  flysafair:            'FA',
  frontier:             'F9',
  garuda:               'GA',
  gol:                  'G3',
  gulfair:              'GF',
  hainan:               'HU',
  hawaiian:             'HA',
  hkexpress:            'UO',
  iberia:               'IB',
  iberiaexpress:        'I2',
  ibomair:              '4D',
  icelandair:           'FI',
  indigo:               '6E',
  itaairways:           'JJ',
  itaairways_old:       'JJ',
  itaairways_v2:        'JJ',
  jal:                  'JL',
  jazeera:              'J9',
  jejuair:              '7C',
  jet2:                 'LS',
  jet2_backup:          'LS',
  jetblue:              'B6',
  jetsmart:             'JA',
  jetstar:              'JQ',
  jinair:               'LJ',
  kenyaairways:         'KQ',
  klm:                  'KL',
  korean:               'KE',
  kuwaitairways:        'KU',
  latam:                'LA',
  level:                'VU',
  linkairways:          'FC',
  lionair:              'JT',
  lot:                  'LO',
  luckyair:             '8L',
  lufthansa:            'LH',
  malaysia:             'MH',
  mea:                  'ME',
  nh:                   'NH',
  nineair:              'AQ',
  nokair:               'DD',
  norwegian:            'DY',
  olympicair_api:       'OA',
  omanair:              'WY',
  peach:                'MM',
  pegasus:              'PC',
  philippineairlines:   'PR',
  pia:                  'PK',
  pngair:               'CG',
  porter:               'PD',
  qantas:               'QF',
  qatar:                'QR',
  rex:                  'ZL',
  royalairmaroc:        'AT',
  royaljordanian:       'RJ',
  rwandair:             'WB',
  ryanair:              'FR',
  saa:                  'SA',
  salamair:             'OV',
  samoaairways:         'OL',
  sas:                  'SK',
  saudia:               'SV',
  scoot:                'TR',
  singapore:            'SQ',
  skyairline:           'H2',
  skyexpress:           'GQ',
  skymark:              'BC',
  smartwings:           'QS',
  solomonairlines:      'IE',
  southwest:            'WN',
  spicejet:             'SG',
  spirit:               'NK',
  spirit_clean:         'NK',
  spring:               'IJ',
  srilankan:            'UL',
  starlux:              'JX',
  suncountry:           'SY',
  sunexpress:           'XQ',
  superairjet:          'IU',
  swiss:                'LX',
  tap:                  'TP',
  thai:                 'TG',
  transavia:            'HV',
  transnusa:            '5R',
  turkish:              'TK',
  twayair:              'TW',
  united:               'UA',
  usbangla:             'BS',
  vietjet:              'VJ',
  vietnamairlines:      'VN',
  virginatlantic:       'VS',
  virginaustralia:      'VA',
  vivaaerobus:          'VB',
  volaris:              'Y4',
  volotea:              'V7',
  vueling:              'VY',
  westjet:              'WS',
  wingo:                'P5',
  wizzair:              'W6',
  zipair:               'ZG',
}

// ── OTAs: connector name → domain ─────────────────────────────────────────────
export const OTA_DOMAINS: Record<string, string> = {
  agoda:            'agoda.com',
  akbartravels:     'akbartravels.com',
  almosafer:        'almosafer.com',
  almundo:          'almundo.com',
  asaptickets:      'asaptickets.com',
  auntbetty:        'auntbetty.com',
  aviasales:        'aviasales.com',
  bookingcom:       'booking.com',
  byojet:           'byojet.com',
  cheapflights:     'cheapflights.com',
  cheapoair:        'cheapoair.com',
  cleartrip:        'cleartrip.com',
  despegar:         'despegar.com',
  edreams:          'edreams.com',
  esky:             'esky.com',
  etraveli:         'etraveli.com',
  expedia:          'expedia.com',
  flightcatchers:   'flightcatchers.com',
  hopper:           'hopper.com',
  iwantthatflight:  'iwantthatflight.com.au',
  ixigo:            'ixigo.com',
  kayak:            'kayak.com',
  kiwi:             'kiwi.com',
  lastminute:       'lastminute.com',
  makemytrip:       'makemytrip.com',
  momondo:          'momondo.com',
  musafir:          'musafir.com',
  onthebeach:       'onthebeach.co.uk',
  opodo:            'opodo.com',
  priceline:        'priceline.com',
  rehlat:           'rehlat.com',
  serpapi_google:   'google.com',
  skiplagged:       'skiplagged.com',
  skyscanner:       'skyscanner.net',
  smartfares:       'smartfares.com',
  tiket:            'tiket.com',
  travelgenio:      'travelgenio.com',
  traveloka:        'traveloka.com',
  travelstart:      'travelstart.com',
  traveltrolley:    'traveltrolley.co.uk',
  travelup:         'travelup.com',
  travix:           'travix.com',
  tripcom:          'trip.com',
  tripsta:          'tripsta.com',
  webjet:           'webjet.com.au',
  wego:             'wego.com',
  yatra:            'yatra.com',
}

// ── URL builders ──────────────────────────────────────────────────────────────

/** Return a logo URL for a given IATA code (e.g. "FR", "W6"). */
export function getLogoByIata(iata: string): string {
  return `https://images.kiwi.com/airlines/64/${iata}.png`
}

/** Return a favicon URL for a given OTA domain. */
export function getFaviconByDomain(domain: string): string {
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=64`
}

/**
 * Get a logo URL from an IATA code (primary, used in results page).
 * Automatically falls back gracefully via onError in the component.
 */
export function getAirlineLogoUrl(airlineCode: string): string {
  return getLogoByIata(airlineCode)
}

/**
 * Get a logo URL from a connector name.
 * Useful for source attribution, connector list pages, etc.
 */
export function getConnectorLogoUrl(connectorName: string): string | null {
  const iata = CONNECTOR_IATA[connectorName]
  if (iata) return getLogoByIata(iata)
  const domain = OTA_DOMAINS[connectorName]
  if (domain) return getFaviconByDomain(domain)
  return null
}
